name: Cypress test
run-name: ${{github.actor}} is learning Github Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm ci

  tests:  
    runs-on: ubuntu-latest
    steps:
    - name: Run Cypress tests
      run: npx cypress run --headless --browser chrome